

export const orders = [
  {
    id: 1,
    nome: "Joao paulo ",
    orcamento: 456.34,
    data: "31/05/2021",
    horario: "tarde",
    profession: "limpador",
    descricaoDoTrabalho: "Para limpar minha casa para mim",
    maisInformacoes: "por favor vem ta",
  },
  {
    id: 1,
    nome: "Joao paulo ",
    orcamento: 456.34,
    data: "31/05/2021",
    horario: "tarde",
    profession: "limpador",
    descricaoDoTrabalho: "Para limpar minha casa para mim",
    maisInformacoes: "por favor vem ta",
  },
  {
    id: 1,
    nome: "Joao paulo ",
    orcamento: 456.34,
    data: "31/05/2021",
    horario: "tarde",
    profession: "limpador",
    descricaoDoTrabalho: "Para limpar minha casa para mim",
    maisInformacoes: "por favor vem ta",
  },
  {
    id: 1,
    nome: "Joao paulo ",
    orcamento: 456.34,
    data: "31/05/2021",
    horario: "tarde",
    profession: "limpador",
    descricaoDoTrabalho: "Para limpar minha casa para mim",
    maisInformacoes: "por favor vem ta",
  },
  {
    id: 1,
    nome: "Joao paulo ",
    orcamento: 456.34,
    data: "31/05/2021",
    horario: "tarde",
    profession: "limpador",
    descricaoDoTrabalho: "Para limpar minha casa para mim",
    maisInformacoes: "por favor vem ta",
  },
  {
    id: 1,
    nome: "Joao paulo ",
    orcamento: 456.34,
    data: "31/05/2021",
    horario: "tarde",
    profession: "limpador",
    descricaoDoTrabalho: "Para limpar minha casa para mim",
    maisInformacoes: "por favor vem ta",
  },
  {
    id: 1,
    nome: "Joao paulo ",
    orcamento: 456.34,
    data: "31/05/2021",
    horario: "tarde",
    profession: "limpador",
    descricaoDoTrabalho: "Para limpar minha casa para mim",
    maisInformacoes: "por favor vem ta",
  },
  
];