

export const orders = [
  {
    id: 1,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 1,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "what is thats ",
  },
  {
    id: 2,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 1,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "",
  },
  {
    id: 3,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 1,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "",
  },
  {
    id: 4,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 2,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "",
  },
  {
    id: 5,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 1,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "",
  },
  {
    id: 6,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 2,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "",
  },
  {
    id: 7,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 3,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "",
  },
  {
    id: 8,
    cliente: "Jmaes kweku",
    prestador: "Kwame kwaku",
    tipo: "Electricista",
    status: 3,
    disponibilidade: "tarde",
    agendamento: "quarta feira",
    acao: "",
  },
];