name: Node.js CI

on:
  push:
    path: "frontend/**"
    branches: [ main ]
  pull_request:
    path: "frontend/**"
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # - run: git config --global user.email ${{secrets.EMAIL}}"
      # - run: git config --global user.name ${{secrets.USERNAME}}"
      # - run: git remote set-url origin https://${{secrets.ACCESS_TOKEN}}@github.com/${{secrets.USERNAME}}/bicudo>.git"
      - run: npm install
      # - run: npm ci
      - run: npm test
      - run: npm run lint
